#pragma once

enum GRID_ENGINE_STATES {
	// IF THE ENGINE IS IN ONE OF THESE TWO STATES, PROGRAM WILL IMMEDIATELY TERMINATE AND RETURN THE ENGINE STATE FROM MAIN
	GRID_ENGINE_SUCCESS = 0, 
	GRID_ENGINE_ERROR = 1, 

	GRID_ENGINE_RUNNING = 2,
	GRID_ENGINE_PAUSED = 3
};

