#pragma once

enum GridEngineStates {
	// IF THE ENGINE IS IN ONE OF THESE TWO STATES, PROGRAM WILL IMMEDIATELY TERMINATE AND RETURN THE ENGINE STATE FROM MAIN
	GRID_ENGINE_SUCCESS, 
	GRID_ENGINE_ERROR, 

	GRID_ENGINE_RUNNING,
	GRID_ENGINE_PAUSED
};

